apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zf2zi7ae5-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:aa18f1c3ad2a2c3f13e5ac233e693ae06e2ac4da@sha256:b04f874064378e4a4d1e4755c8d4e13961c6a26f355ae62d17ad9b7e3d42b09d
          name: container-image
