apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zf2zi7ae5-dotnet-basic
  janus-idp.io/tekton: zf2zi7ae5-dotnet-basic
  backstage.io/kubernetes-id: zf2zi7ae5-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zf2zi7ae5-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
